// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/buyer_demand/repo.go

// Package mock_address is a generated GoMock package.
package mock_address

import (
	context "context"
	reflect "reflect"

	entity "github.com/HomesNZ/buyer-demand/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Populate mocks base method.
func (m *MockRepo) Populate(ctx context.Context, buyerDemands entity.BuyerDemands) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Populate", ctx, buyerDemands)
	ret0, _ := ret[0].(error)
	return ret0
}

// Populate indicates an expected call of Populate.
func (mr *MockRepoMockRecorder) Populate(ctx, buyerDemands interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Populate", reflect.TypeOf((*MockRepo)(nil).Populate), ctx, buyerDemands)
}
